language: cpp

os:
    - linux
    - osx

branches:
  only:
    - develop

compiler:
    - gcc
    - clang

matrix:
    exclude:
      - os: osx
      compiler: gcc

install:
    - git clone https://github.com/sdalton1/thrust.git
    - export THRUST_PATH=$PWD/thrust
    - cd testing

script:
    - scons compiler=g++ backend=omp
    - cd device_omp_release
    - ./tester --verbose
