language: cpp
sudo: required
dist: trusty

os:
    - linux

branches:
  only:
    - develop

addons:
    apt:
      sources:
          - llvm-toolchain-precise
          - ubuntu-toolchain-r-test
      packages:
          - clang-3.9

compiler:
    - gcc
    - clang

env:
    - THRUST_VERSION=1.7.2
    - THRUST_VERSION=1.8.3
    - THRUST_VERSION=master

install:
    # - if [ "$CC" = "clang" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
    - sudo apt-get -y install libiomp-dev
    - sudo ln -s /usr/bin/clang-3.9 /usr/bin/clang
    - git clone -b $THRUST_VERSION https://github.com/sdalton1/thrust.git
    - export THRUST_PATH=$PWD/thrust
    - cd testing

script:
    - scons compiler=$CC backend=omp && cd device_omp_release && ./tester --verbose

